workflows:
  ios-release:
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'feature/*'
          include: true
        - pattern: 'main'
          include: true
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.dezetingz.yuhBlockin"

    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE
          keychain add-certificates
          xcode-project use-profiles --export-options-plist=$HOME/export_options.plist

      - name: Auto-increment build number
        script: |
          # Get current build number from pubspec.yaml
          CURRENT_BUILD=$(grep -o 'version: [0-9.]*+[0-9]*' pubspec.yaml | grep -o '+[0-9]*' | tr -d '+')
          # Increment by 1
          NEW_BUILD=$((CURRENT_BUILD + 1))
          # Update pubspec.yaml with new build number
          sed -i '' "s/version: \([0-9.]*\)+[0-9]*/version: \1+$NEW_BUILD/" pubspec.yaml
          echo "Build number updated: $CURRENT_BUILD -> $NEW_BUILD"

      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

  android-release:
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    name: Android Release Build
    max_build_duration: 30
    instance_type: linux_x2

    environment:
      flutter: stable
      java: 11
      groups:
        - google_play_credentials

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
